config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    resources :communities, only: %w[index create destroy show]
    resources :submissions, only: %w[index create destroy new show]
  end

  root 'submissions#index'

  resources :comments, only: %w[create destroy new]
  resources :communities, only: %w[create destroy new show]
  resources :submissions, only: %w[index create destroy new show]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :parent, class_name: 'Comment', optional: true
  belongs_to :submission
  has_many :replies, class_name: 'Comment', dependent: :destroy, foreign_key: 'parent_id'

  validates :message, length: { minimum: 1 }
  validates :parent, presence: { unless: -> { parent_id.blank? } }
end

app/models/community.rb
# frozen_string_literal: true

class Community < ApplicationRecord
  has_many :submissions, dependent: :destroy

  validates :name, length: { minimum: 4 }, uniqueness: true
end

app/models/submission.rb
# frozen_string_literal: true

class Submission < ApplicationRecord
  belongs_to :community
  has_many :comments, dependent: :destroy

  validates :title, length: { minimum: 5 }
  validates :url, url: true

  has_many :root_comments, ->{ where parent_id: nil}, class_name: 'Comment'
end

app/controllers/api/communities_controller.rb
# frozen_string_literal: true

module Api
  class CommunitiesController < ApplicationController
    skip_before_action :verify_authenticity_token
    before_action :set_community, only: %i[show destroy]

    def create
      @community = Community.new(community_params)

      if @community.save
        render json: @community
      else
        render :json => { :errors => @community.errors.full_messages }, :status => 422
      end
    end

    def destroy
      id = params[:id]
      Community.find(id).destroy
      head :no_content
    end

    def new
      @community = Community.new
    end

    def show
      id = params[:id]
      render json: Community.find(id), include: [submissions: { include: [:community, :comments] }]
    end

    def index
      render json: Community.all
    end

    private

    def community_params
      params.require(:community).permit(:name)
    end

    def set_community
      @community = Community.find(params[:id])
    end
  end
end

app/controllers/api/submissions_controller.rb
# frozen_string_literal: true

module Api
  class SubmissionsController < ApplicationController
    skip_before_action :verify_authenticity_token
    before_action :set_submission, only: %i[destroy show]

    def get_submissions
      @submissions = Submission.all.reverse_order
      render json: @submissions
    end

    def create
      @submission = Submission.new(submission_params)

      if @submission.save
        render json: @submission
      else
        render :json => { :errors => @submission.errors.full_messages }, :status => 422
      end
    end

    def destroy
      id = params[:id]
      Submission.find(id).destroy
      head :no_content
    end

    def index
      @submissions = Submission.all.reverse_order
      render json: @submissions, include: [:community, :comments]
    end

    def new
      @submission = Submission.new(community_id: params['community_id'])
    end

    def show
      id = params[:id]
      render json: Submission.find(id), include: [comments: {}, community: {}]
    end

    private

    def set_submission
      @submission = Submission.find(params[:id])
    end

    def submission_params
      params.require(:submission).permit(:title, :url, :community_id)
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :set_comment, only: %i[destroy show]

  def create
    @comment = Comment.new(comment_params)

    if @comment.save
      redirect_to @comment.submission, notice: 'Comment was successfully created.'
    elsif @comment.errors.include?(:parent) || @comment.errors.include?(:submission)
      redirect_to root_path, flash: { error: 'Could not save the comment.' }
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @comment.destroy
    redirect_to submission_path(@comment.submission), notice: 'Comment was successfully destroyed.'
  end

  def new
    @comment = Comment.new(comment_params)
  end

  private

  def comment_params
    params.require(:comment).permit(:message, :submission_id, :parent_id)
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end
end

app/controllers/communities_controller.rb
# frozen_string_literal: true

class CommunitiesController < ApplicationController
  before_action :set_community, only: %i[show destroy]

  def create
    @community = Community.new(community_params)

    if @community.save
      redirect_to @community, notice: 'Community was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @community.destroy
    redirect_to root_path, notice: 'Community was successfully destroyed.'
  end

  def new
    @community = Community.new
  end

  def show; end

  private

  def community_params
    params.require(:community).permit(:name)
  end

  def set_community
    @community = Community.find(params[:id])
  end
end

app/controllers/submissions_controller.rb
# frozen_string_literal: true

class SubmissionsController < ApplicationController
  before_action :set_submission, only: %i[destroy show]

  def create
    @submission = Submission.new(submission_params)

    if @submission.save
      redirect_to @submission, notice: 'Submission was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @submission.destroy
    redirect_to root_path, notice: 'Submission was successfully destroyed.'
  end

  def index
    if stale?([Submission.all, Community.all, Comment.all])
      @submissions = Submission.all.reverse_order
    end
  end

  def new
    @submission = Submission.new(community_id: params['community_id']) if stale?(Community.all)
  end

  def show
    fresh_when([@submission, @submission.community, @submission.comments])
  end

  private

  def set_submission
    @submission = Submission.find(params[:id])
  end

  def submission_params
    params.require(:submission).permit(:title, :url, :community_id)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def bootstrap_class_for(flash_type)
    { success: 'alert-success', error: 'alert-danger', alert: 'alert-warning', notice: 'alert-success' }[flash_type] || flash_type.to_s
  end

  def flash_messages(_opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type.to_sym)} fade in") do
               concat content_tag(:button, 'x', class: 'close', data: { dismiss: 'alert' })
               concat message
             end)
    end
    nil
  end
end

app/helpers/submissions_helper.rb
module SubmissionsHelper

  def cache_key_for_submission_table
    "submission-table-#{Submission.maximum(:updated_at)}-#{Comment.maximum(:updated_at)}"
  end

  def cache_key_for_submission_row(submission)
    "submission-#{submission.id}-#{submission.updated_at}-#{submission.comments.count}"
  end
end

app/views/application/_listing.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Url</th>
      <th>Community</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% submissions.each do |submission| %>
      <% cache(cache_key_for_submission_row(submission)) do %>
        <tr>
          <td><%= link_to(submission.title, submission.url) %></td>
          <td><%= submission.url %></td>
          <td><%= link_to submission.community.name, submission.community %></td>
          <td><%= link_to "#{submission.comments.size} comments", submission, class: 'btn btn-primary btn-sm'  %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/comments/_comment.html.erb
<div class="card bg-light">
  <div class="card-body">
    <%= comment.message %><br>
    <%= link_to("Reply",
                {
                  controller: "comments",
                  action: "new",
                  comment: {parent_id: comment.id, submission_id: comment.submission.id}
                },
                class: 'btn btn-primary btn-sm') %>
    <%= link_to("Delete",
                comment_path(comment),
                class: 'btn btn-danger btn-sm',
                data: { confirm: 'Are you sure?'},
                method: :delete) %>

    <%= render comment.replies %>
  </div>
</div>

app/views/comments/_form.html.erb
<h2>Submission: <%= @comment.submission.title %></h2>
<%= "<h3>Parent: #{@comment.parent.message}</h3>".html_safe if @comment.parent %>

<%= simple_form_for(@comment) do |form| %>
  <%= form.hidden_field :submission_id, value: @comment.submission.id %>
  <%= form.hidden_field :parent_id, value: @comment.parent.id if @comment.parent %>

  <%= form.input :message, input_html: { class: 'form-control' }, wrapper_html: { class: 'form-group' } %>
  <%= form.button :submit, class: 'btn-primary btn-sm' %>
<% end %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

app/views/communities/_form.html.erb
<%= simple_form_for(@community) do |form| %>
  <%= form.input :name, input_html: { class: 'form-control' }, wrapper_html: { class: 'form-group' } %>
  <%= form.button :submit, class: 'btn-primary btn-sm' %>
<% end %>

app/views/communities/new.html.erb
<h1>New Community</h1>

<%= render 'form' %>

app/views/communities/show.html.erb
<h1><%= @community.name %></h1>

<%= render partial: 'listing', locals: { submissions: @community.submissions.reverse_order } %>

<%= link_to 'New Submission', new_submission_path(community_id: @community.id), class: 'btn btn-primary' %>

<%= link_to("Delete Community", community_path(@community), class: 'btn btn-danger', data: { confirm: 'Are you sure?'}, method: :delete) %>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <title>Demo</title>
    <link href="data:image/x-icon;base64,YourBase64StringHere" rel="icon" type="image/x-icon" />

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">

    <%= csrf_meta_tags %>
    <%= javascript_pack_tag "application" %>
  </head>
  <body>
    <div class="container">
      <nav class="navbar navbar-dark bg-dark">
        <a class="navbar-brand" href="/">Demo App</a>
      </nav>
      <%= flash_messages %>
      <div id="app_root"></div>
      <%= yield %>
    </div>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/submissions/_form.html.erb
<%= simple_form_for(@submission) do |form| %>
  <%= form.input :title, input_html: { class: 'form-control' }, wrapper_html: { class: 'form-group' } %>
  <%= form.input :url, input_html: { class: 'form-control' }, wrapper_html: { class: 'form-group' } %>
  <%= form.input :community_id, collection: Community.all, include_blank: false, input_html: { class: 'form-control' }, wrapper_html: { class: 'form-group' } %>
  <%= form.button :submit, class: 'btn-primary btn-sm' %>
<% end %>

app/views/submissions/index.html.erb
<% cache(cache_key_for_submission_table) do %>
  <h1>Front Page!</h1>

  <%= render partial: 'listing', locals: { submissions: @submissions } %>

  <%= link_to 'New Submission', new_submission_path, class: 'btn btn-primary' %>
  <%= link_to 'New Community', new_community_path, class: 'btn btn-primary' %>
<% end %>

app/views/submissions/new.html.erb
<h1>New Submission</h1>

<%= render 'form' %>

app/views/submissions/show.html.erb
<h1><%= @submission.title %> (via <%= link_to @submission.community.name, @submission.community %>)</h1>
<p><%= link_to @submission.url %></p>

<div>
  <%= link_to("Comment", {controller: "comments", action: "new", comment: {submission_id: @submission.id}}, {class: 'btn btn-primary btn-sm'} ) %>
  <%= link_to("Delete Submission", submission_path(@submission), class: 'btn btn-danger btn-sm', data: { confirm: 'Are you sure?'}, method: :delete) %>
</div>

<% if @submission.root_comments.size > 0 %>
  <div>
    Comments:<br>
    <%= render @submission.root_comments %>
  </div>
<% end %>